version: '3.8'
services:
  backend:
    container_name: backend-fastapi
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8008:8008"
    environment:
      - QDRANT_URL=http://db:6333
      - QDRANT_API_KEY=API_KEY
      - ENCODER_MODEL_PATH=backend/model/encoder_model.keras
    depends_on:
      - db

  frontend:
    container_name: frontend-react
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - backend

  db:
    container_name: qdrant
    image: "qdrant/qdrant"
    environment:
      - QDRANT__STORAGE__STORAGE_PATH=/var/lib/qdrant
    volumes:
      - qdrant_data:/var/lib/qdrant
    ports:
      - "6333:6333"

volumes:
  qdrant_data:
